import 'package:flutter/material.dart';
import 'screens/splash_screen.dart';
import 'screens/dashboard.dart';
import 'screens/leaderboard.dart';
import 'screens/trophies.dart';
import 'screens/settings_screen.dart';
import 'screens/username_screen.dart';

import 'screens/beginner_level.dart';
import 'screens/beginner_details.dart';
import 'screens/beginner_quiz_screen.dart';

import 'screens/inter_level.dart';
import 'screens/inter_details.dart';
import 'screens/inter_quiz_screen.dart';

import 'screens/advance_level.dart';
import 'screens/advance_details.dart';
import 'screens/advance_quiz_screen.dart';

import 'package:supabase_flutter/supabase_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Supabase.initialize(
    url: 'https://relokobdxcseabousdwo.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlbG9rb2JkeGNzZWFib3VzZHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMjczNDUsImV4cCI6MjA1MzcwMzM0NX0.DbPEEFjvq1AN6YZgJ_9zDP9Q0kWZH0V6PxwSRMSyaHg', // Replace with your Supabase anon key
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cybersecurity Learning App',
      theme: ThemeData(
        primaryColor: Colors.purpleAccent,
        colorScheme: ColorScheme.dark(
          primary: Color(0xFF00FF9D),
          secondary: Color(0xFF2A75FF),
          error: Color(0xFFFF4D4D),
          // background: const Color(0xFF0A192F),
          surface: Color(0xFFEA80FC),
        ),
        textTheme: TextTheme(
          headlineLarge: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
          bodyMedium: TextStyle(color: Colors.black),
        ),
      ),
      initialRoute: '/', // Starting route
      routes: {
        '/': (context) => SplashScreen(),  // Splash screen route
        '/input_screen': (context) => UsernameScreen(),
        '/dashboard': (context) => Dashboard(),  // Main dashboard route
        '/beginner': (context) => BeginnerLevel(),  // Beginner level route
        '/intermediate': (context) => IntermediateLevel(),
        '/advance': (context) => AdvancedLevel(),  // Beginner level route// Beginner level route
        '/leaderboard': (context) => Leaderboard(),  // Leaderboard route
        '/trophies': (context) => Trophies(),  // Trophies route
        '/settings': (context) => SettingsScreen(),

        '/topic/phishing': (context) => TopicDetailScreen(
          title: "Phishing",
          article: "Phishing: A Growing Cyber Threat\n\n"
            "Phishing is a type of cyberattack in which attackers attempt to deceive individuals into revealing sensitive information, such as usernames, passwords, credit card details, or other personal data, by pretending to be a trustworthy entity. This tactic is among the most common and damaging methods used by cybercriminals, as it leverages social engineering to exploit human psychology. The effectiveness of phishing lies in its ability to manipulate victims into acting quickly and without questioning the authenticity of the request.\n\n"
            "Typically, phishing is carried out through fraudulent emails, text messages, or websites that appear legitimate but are actually designed to steal the victim’s data. Attackers often impersonate well-known organizations, such as banks, e-commerce platforms, or even colleagues in a corporate environment, making the attack seem more convincing. They might create fake email addresses or URLs that closely resemble those of the real entities they are impersonating. These communications might appear urgent, with messages claiming that the victim's account is compromised or that immediate action is required to avoid some kind of penalty or loss.\n\n"
            "How Phishing Works\n\n"
            "A typical phishing attack begins when an individual receives a message that looks like it comes from a trusted source, such as a bank, a social media site, or even a government agency. The message often includes a request to click a link or open an attachment, which is where the danger lies. The link usually directs the victim to a fraudulent website designed to capture their personal information. The attachment, if downloaded, might contain malware or ransomware that could compromise the victim’s device.\n\n"
            "Phishing emails or messages often include common tactics to encourage immediate action. For example, the attacker may tell the victim that their account has been compromised or that they must verify their identity to prevent their account from being locked. Other common techniques involve offering a prize, discount, or exclusive offer to tempt the recipient into clicking on the malicious link or downloading the attachment.\n\n"
            "The fraudulent websites that are part of these phishing schemes are often designed to closely mimic the legitimate site they are imitating. They may include logos, brand colors, and other design elements that appear identical to the real site. However, a closer inspection may reveal discrepancies, such as misspelled words, slight variations in the URL, or a lack of security certificates (indicated by (HTTPS) or a padlock icon in the browser address bar). These details can serve as red flags for anyone aware of the risks, but they can be easily overlooked by an unsuspecting user.\n\n"
                "Types of Phishing Attacks\n\n"
                "Phishing attacks come in several variations, each targeting users in different ways:\n\n"
                "1. Email Phishing: This is the most common form of phishing, where attackers send fraudulent emails posing as legitimate organizations. These emails typically contain a link to a fake website or an attachment that, when clicked, can steal the victim's data or infect their device.\n\n"
                "2. Spear Phishing: Unlike generic phishing attempts that target a broad audience, spear phishing is highly targeted. Attackers research their victims, often using information gleaned from social media or other online sources, to craft a personalized attack. This makes spear phishing harder to detect, as the message may appear highly legitimate and relevant to the victim.\n\n"
                "3. Smishing: This type of phishing involves the use of text messages (SMS) to deceive victims into clicking on malicious links or downloading harmful files. Smishing is on the rise as more people use smartphones for banking and other sensitive activities.\n\n"
                "4. Vishing: Also known as voice phishing, vishing involves phone calls from attackers impersonating legitimate institutions or services. The attacker may ask for sensitive information or direct the victim to a fraudulent website or toll-free number.\n\n"
                "5. Pharming: While not exactly the same as traditional phishing, pharming involves redirecting a legitimate website’s traffic to a fraudulent site without the victim’s knowledge. This typically occurs when the attacker manipulates the victim’s DNS settings or compromises the website’s server.\n\n"
                "Why Phishing is Effective\n\n"
                "Phishing attacks are particularly effective because they exploit the inherent trust people place in email, phone calls, and websites. When individuals receive a message that appears to come from a trusted source, they are more likely to act without thoroughly verifying its authenticity. Cybercriminals exploit this human vulnerability by creating a sense of urgency or offering something enticing, such as a prize or an account update. This urgency can cloud the victim’s judgment and prevent them from stopping to think critically before clicking on a link or entering personal information.\n\n"
            "Additionally, many people are not fully aware of how to spot phishing attempts. The attackers often go to great lengths to make their communications look legitimate, using techniques such as mimicking the official tone and branding of trusted companies. Even those who are familiar with the risks of phishing may fall victim to a well-crafted and convincing attack.\n\n"
            "How to Protect Yourself from Phishing\n\n"
            "Given the growing prevalence and sophistication of phishing attacks, it is essential for individuals and organizations to take steps to protect themselves. Here are some basic guidelines to follow:\n\n"
            "1. Be Skeptical of Unsolicited Communications: If you receive an unexpected email, text message, or phone call requesting sensitive information, be cautious. Legitimate companies will never ask for passwords or other personal details via email or text.\n\n"
            "2. Examine URLs Carefully: Always check the website’s URL before entering any personal information. Look for subtle misspellings or variations in the domain name. If in doubt, type the website address directly into your browser instead of clicking on a link.\n\n"
            "3. Enable Multi-Factor Authentication (MFA): MFA provides an additional layer of security by requiring more than just a password to access an account. Even if your credentials are stolen, MFA can help prevent unauthorized access.\n\n"
            "4. Keep Software Up to Date: Ensure that your operating system, antivirus software, and web browser are all updated to protect against known vulnerabilities that attackers might exploit.\n\n"
            "5. Use Anti-Phishing Tools: Many modern web browsers and email services offer built-in anti-phishing tools that can help detect malicious websites or emails. Make sure these features are enabled.\n\n"
            "6. Verify Suspicious Requests: If you receive an unexpected request for personal information, contact the organization directly using official contact details (not the ones provided in the suspicious message).\n",
            videoId: '3GBmpqhQI8s',
        ),

        '/topic/password_management': (context) => TopicDetailScreen(
          title: "Password Management",
          article: "Password management refers to the practices, tools, and strategies used to securely create, store, and manage passwords to protect access to sensitive accounts and systems. Effective password management involves using strong, unique passwords for each account, avoiding the reuse of passwords, and utilizing techniques like multi-factor authentication (MFA) for added security. To handle the complexity of remembering multiple passwords, password managers are commonly used. These tools securely store and encrypt passwords, allowing users to access their accounts easily without needing to remember every password. Additionally, password management practices often include periodic password updates and monitoring for breaches. Proper password management reduces the risk of unauthorized access and is a critical aspect of maintaining personal and organizational cybersecurity. \n\n"
            "Passwords are the keys to accessing our digital lives, from email accounts to banking services. Yet, despite their importance, many people still fall into the trap of using weak, reused, or easily guessable passwords. This exposes users to significant risks, including identity theft, financial loss, and data breaches. To prevent these risks, password management is essential in today’s increasingly digital world. \n\n"
            "Effective password management starts with the creation of strong passwords. A strong password is typically at least 12 characters long, combining upper and lowercase letters, numbers, and special characters. It should avoid using personal information, such as names or birthdates, which can be easily guessed or obtained from social media profiles. Instead, it’s recommended to use random combinations of characters that do not form recognizable words. \n\n"
            "To ensure strong passwords, one must also avoid reusing passwords across multiple accounts. While it may seem convenient to use the same password for several accounts, this practice significantly increases the risk of a domino effect in case one account is compromised. If attackers gain access to one of your accounts and you’ve reused the same password elsewhere, they can potentially access your other accounts as well. This makes it crucial to use a different, strong password for each account to limit the damage if a breach occurs.\n\n"
            "However, the reality is that remembering dozens of complex passwords for different accounts can be overwhelming. This is where password managers come in. A password manager is a tool that securely stores and encrypts passwords, so users only need to remember one master password to access all their stored credentials. These tools often generate strong, random passwords for each account and automatically fill in login information on websites and apps, reducing the risk of password reuse and human error.\n\n"
            "Password managers are not just for individuals; organizations also benefit from these tools. For businesses, password managers help ensure employees use strong, unique passwords for work accounts. They can also facilitate secure sharing of passwords among team members, reducing the need for insecure methods like emailing or writing down passwords. Some password managers even offer enterprise features like monitoring for password breaches and enforcing security policies.\n\n"
            "Beyond the use of strong passwords and password managers, an additional layer of security comes from multi-factor authentication (MFA). MFA requires users to provide two or more verification factors to gain access to an account. For example, after entering a password, a user may be asked to confirm their identity by entering a one-time code sent to their phone or generated by an authenticator app. This greatly increases security by ensuring that even if an attacker knows your password, they still need a second factor to access your account.\n\n"
            "While MFA provides significant protection, it is not foolproof. Attackers may still try to bypass MFA by targeting users through phishing attacks, SIM swapping, or social engineering tactics. As a result, it’s essential to remain vigilant and cautious when interacting with suspicious messages or requests for personal information.\n\n"
            "Periodic password updates are another important aspect of good password management. Over time, passwords can be exposed due to data breaches or other vulnerabilities, so updating them regularly can help reduce the risk of unauthorized access. It’s important to prioritize updating passwords for accounts that store sensitive information or have access to financial resources. While frequent changes may seem cumbersome, many password managers can automate this process, making it easier to maintain up-to-date security.\n\n"
            "In addition to periodic updates, monitoring for breaches is critical to maintaining password security. Data breaches are unfortunately common, and they can often result in leaked passwords or other sensitive information. Password managers often provide breach monitoring services, alerting users if their stored passwords appear in known breaches. If a password manager detects a breach, the user can take immediate action, such as changing their passwords for affected accounts and enabling additional security features like MFA.\n\n"
            "Password management is also essential for organizations to prevent unauthorized access to internal systems. In business environments, passwords may be shared across teams or with third-party vendors, making it important to have clear policies and procedures in place to safeguard those credentials. Many businesses use centralized password management systems, which allow administrators to monitor, manage, and enforce password policies for employees and contractors.\n\n"
            "Finally, the importance of educating users about password management cannot be overstated. Employees and individuals alike need to understand the risks associated with poor password practices and the steps they can take to protect themselves. Password management tools, MFA, and regular security training all play a role in ensuring that users are equipped to secure their accounts effectively.\n\n"
            "In conclusion, password management is a cornerstone of digital security. Whether for personal or organizational use, managing passwords effectively involves using strong, unique passwords, employing tools like password managers, enabling multi-factor authentication, updating passwords regularly, and monitoring for breaches. By implementing these best practices, individuals and organizations can significantly reduce the risk of unauthorized access and keep their sensitive information secure in an increasingly interconnected world.\n",
          videoId: '867tece6KZk',
        ),

        '/topic/malware': (context) => TopicDetailScreen(
          title: "Malware",
          article:
            "Malware (short for 'malicious software') is a type of software designed to infiltrate, damage, or disrupt computer systems, networks, or devices without the user's consent. It encompasses a variety of harmful programs, including viruses, worms, Trojans, ransomware, spyware, adware, and rootkits, each with specific malicious functions. For example, viruses attach themselves to legitimate files and spread when those files are shared, while ransomware encrypts a user's files and demands payment for decryption. Malware can be delivered through infected emails, websites, software downloads, or external devices, and once activated, it can steal sensitive information, disrupt system operations, or even grant attackers remote access to affected devices. The primary goal of malware is often to steal data, compromise security, or generate profits for cybercriminals, making it a significant threat to both individual users and organizations.\n\n"
            "Malware has become one of the most significant cybersecurity threats of the modern age. It continues to evolve, with cybercriminals constantly developing new methods to bypass security measures and infect systems. With the increasing amount of personal and corporate data stored digitally, the potential damage caused by malware is immense. Whether it’s personal financial information, business-critical data, or sensitive government files, malware poses a serious risk to confidentiality, integrity, and availability.\n\n"
            "There are several types of malware, each designed to serve different malicious purposes. Understanding these types is essential in recognizing how they function and how to protect against them. Some of the most common types include:\n\n"
            "1. **Viruses**: A virus is a type of malware that attaches itself to a legitimate file or program and spreads to other files when that program is executed. Viruses can cause a variety of problems, including corrupting data, slowing down systems, or even deleting files. The spread of a virus typically happens through infected email attachments, software downloads, or file sharing.\n\n"
            "2. **Worms**: Worms are similar to viruses but differ in that they do not need a host program to spread. They can self-replicate and spread across networks, often causing widespread damage in a short period of time. Worms can exploit vulnerabilities in software or operating systems to propagate, and they can take up significant bandwidth, disrupting network operations.\n\n"
            "3. **Trojans**: A Trojan horse is malware that disguises itself as a legitimate program or file to trick users into downloading it. Once installed, Trojans can perform a variety of harmful actions, such as stealing data, creating backdoors for remote access, or even installing other types of malware. Trojans often spread through phishing emails or deceptive websites.\n\n"
            "4. **Ransomware**: Ransomware is a particularly dangerous type of malware that locks or encrypts a user's files and demands a ransom in exchange for the decryption key. In some cases, the attacker may threaten to leak sensitive data if the ransom is not paid. Ransomware can have devastating consequences, especially for businesses that rely on access to critical data.\n\n"
            "5. **Spyware**: Spyware is designed to secretly monitor a user's activity, including keystrokes, browsing habits, and online behavior. It often collects sensitive information such as login credentials, financial details, and personal data. Spyware can be installed through malicious websites, software downloads, or bundled with other software.\n\n"
            "6. **Adware**: While not always harmful, adware is a type of malware that displays unwanted advertisements or redirects users to specific websites. Adware can slow down systems, cause browser crashes, and lead to security vulnerabilities. Some forms of adware may also track user behavior for targeted advertising.\n\n"
            "7. **Rootkits**: Rootkits are a particularly insidious form of malware designed to gain unauthorized access to a system and hide the presence of other malicious programs. Once installed, rootkits can provide cybercriminals with remote access to a system, allowing them to steal data, install additional malware, or monitor the system without detection.\n\n"
            "Malware can be delivered in a variety of ways, often exploiting vulnerabilities in software or tricking users into taking certain actions. Some common delivery methods include:\n\n"
            "1. **Email Attachments**: Many malware attacks begin with phishing emails that contain malicious attachments. These attachments often appear to be harmless documents or files, such as invoices or updates. Once opened, the attachment installs malware onto the system.\n\n"
            "2. **Malicious Links**: Malware can also be delivered through malicious links in emails, text messages, or websites. Clicking on these links may lead to a website that downloads malware onto the user’s device or directs them to a phishing site designed to steal login credentials.\n\n"
            "3. **Software Downloads**: Malware can be embedded in software or apps available for download from untrustworthy sources. Even downloading seemingly legitimate software can result in malware installation if the software has been tampered with.\n\n"
            "4. **External Devices**: Malware can spread through USB drives or external hard drives. If an infected device is connected to a computer, it can automatically install malware or spread to other systems connected to the same network.\n\n"
            "Once malware has infected a system, its impact can vary. In some cases, the malware might remain dormant for a period before activating, while in other cases, it may cause immediate disruption. Some malware is designed to steal sensitive data, such as login credentials, banking information, or personally identifiable information. This data is then sold or used for identity theft.\n\n"
            "Other types of malware are used to disrupt system operations, often rendering devices or entire networks unusable. For example, ransomware can lock files or demand payment for access, while worms can flood networks with excessive traffic, causing slowdowns or crashes.\n\n"
            "One of the most concerning aspects of malware is the ability to grant remote access to cybercriminals. This means that attackers can take control of infected systems without the user’s knowledge, allowing them to steal data, install more malware, or even use the system for botnet attacks, where large numbers of compromised devices are used to carry out attacks on other systems.\n\n"
            "To protect against malware, users must take several precautionary measures. These include:\n\n"
            "1. **Using Antivirus Software**: Installing and regularly updating antivirus software is one of the most effective ways to detect and block malware before it can cause harm. Antivirus programs scan files and programs for known malware signatures and can block malicious activities in real-time.\n\n"
            "2. **Keeping Software Up to Date**: Many forms of malware exploit vulnerabilities in outdated software. Regularly updating operating systems, applications, and antivirus programs ensures that security patches are applied to protect against known threats.\n\n"
            "3. **Avoiding Suspicious Links and Attachments**: Users should be cautious when clicking on links or downloading attachments from unknown or untrusted sources. Phishing emails and malicious websites often disguise themselves as legitimate communications or sites.\n\n"
            "4. **Enabling Firewall Protection**: A firewall acts as a barrier between your device and the internet, blocking unauthorized access attempts. Enabling a firewall helps protect against malware attempting to exploit open ports or vulnerabilities.\n\n"
            "In conclusion, malware is a constant and evolving threat to digital security. It can have severe consequences, ranging from data theft to system disruption and financial loss. Understanding the different types of malware, how it spreads, and how to protect against it is crucial for both individual users and organizations. By implementing strong security practices and staying vigilant, users can significantly reduce the risk of malware infections and safeguard their systems and data.\n",
          videoId: 'cNVwkLo1Snw',
        ),

        '/topic/social_engineering': (context) => TopicDetailScreen(
          title: "Social Engineering",
          article:
            "Social engineering is a manipulation technique used by cybercriminals to deceive individuals into divulging confidential information, granting unauthorized access, or performing actions that compromise security. Unlike technical hacking methods, social engineering relies on psychological manipulation, exploiting human behavior, trust, or emotions. The primary goal of social engineering is to trick victims into making mistakes or acting in a way that benefits the attacker. \n\n"
            "Cybercriminals leverage various social engineering tactics to achieve their objectives, and these tactics are often difficult to detect because they exploit human psychology rather than relying on technical vulnerabilities. Some of the most common types of social engineering attacks include phishing, pretexting, baiting, and tailgating. \n\n"
            "1. **Phishing**: Phishing is one of the most widespread forms of social engineering, involving fraudulent emails or websites that are designed to trick users into revealing personal information such as usernames, passwords, or financial details. The attacker might impersonate a trusted entity, such as a bank or popular service, and convince the target to click on a malicious link or download an infected attachment. Phishing attacks are particularly effective because they play on people's trust and urgency, often claiming that the victim's account has been compromised or that immediate action is needed. \n\n"
            "2. **Pretexting**: Pretexting is a social engineering tactic where an attacker creates a fabricated scenario or pretext to obtain sensitive information. The attacker might pose as a colleague, IT support, or even a government official, and ask the victim for personal data or access to a secure system. The key to pretexting is that the attacker convinces the victim that they are authorized to request such information, often using information about the victim that has been obtained through research or previous interactions. \n\n"
            "3. **Baiting**: Baiting involves offering something enticing, such as free software, a prize, or exclusive access to an event, in exchange for the victim taking a specific action. The bait may come in the form of a physical item, such as a USB drive, which contains malware that is activated once inserted into a victim's computer. Alternatively, baiting can be done online, where attackers promise rewards in exchange for login credentials or personal information. The victim is lured into compromising their security in hopes of gaining something valuable. \n\n"
            "4. **Tailgating**: Tailgating, also known as piggybacking, is a physical security breach where an attacker gains unauthorized access to a restricted area by following an authorized person into the area. For example, an attacker might wait for an employee to enter a secure building and then walk closely behind them, pretending to be an authorized person. Tailgating can also occur in workplaces with access-controlled doors where employees hold the door open for someone they don't recognize. While this tactic may seem simple, it can be highly effective in environments with lax security awareness. \n\n"
            "Social engineering attacks are particularly dangerous because they target the human element, which is often the weakest link in an organization's security. Even with the most robust technical defenses like firewalls, encryption, and anti-malware software, attackers can bypass these protections by manipulating individuals into revealing sensitive information or performing actions that undermine security. \n\n"
            "One of the reasons social engineering is so effective is that it takes advantage of common human emotions, such as trust, fear, curiosity, or greed. For example, a phishing email that threatens account suspension unless immediate action is taken plays on the victim's fear of losing access to an important service. Similarly, the promise of free software or a prize taps into the victim's curiosity or desire for something for nothing. \n\n"
            "Organizations can mitigate the risks of social engineering attacks by promoting cybersecurity awareness among employees and implementing security training programs. Training should focus on recognizing the signs of phishing, the importance of verifying requests for sensitive information, and the risks associated with tailgating. Additionally, organizations should enforce strict security protocols, such as requiring multi-factor authentication (MFA) and regularly auditing access to sensitive areas. \n\n"
            "In conclusion, social engineering remains a powerful and dangerous tool in the hands of cybercriminals. By understanding the different types of social engineering tactics and raising awareness, individuals and organizations can better protect themselves against these deceptive attacks. Awareness and vigilance are key to safeguarding personal and corporate security from the manipulation tactics that exploit human behavior. ",
          videoId: 'uvKTMgWRPw4',
        ),

        '/topic/secure_browsing_and_https': (context) => TopicDetailScreen(
          title: "Secure Browsing and HTTPS",
          article:
            "Secure browsing refers to practices and technologies that ensure online activities, such as web browsing, remain safe from threats like data interception, malware, and privacy violations. As our digital lives become increasingly interconnected, protecting sensitive information during online activities has become more important than ever. Secure browsing helps protect users from malicious actors and unauthorized access to personal data. \n\n"
            "One of the primary methods to secure browsing is through HTTPS (Hypertext Transfer Protocol Secure), which is an extension of HTTP that uses encryption to protect the communication between a user's browser and a website. HTTPS is indicated by the padlock icon in the browser's address bar, showing that the website is using encryption to secure the data transmitted between the user and the site. \n\n"
            "HTTPS employs SSL/TLS encryption to ensure that any data exchanged, including passwords, credit card numbers, and personal information, remains encrypted and unreadable to third parties, such as hackers, even if they intercept the transmission. This encryption ensures that sensitive information cannot be accessed or tampered with by attackers, making HTTPS a fundamental component of secure browsing. \n\n"
            "Without HTTPS, data exchanged between the user and a website is sent in plain text, meaning that anyone with access to the network, such as hackers or cybercriminals, can easily intercept and steal that information. This is especially risky when using public Wi-Fi networks, where attackers can deploy man-in-the-middle attacks to capture sensitive data. HTTPS mitigates these risks by ensuring that all data sent between the user's browser and the website is encrypted. \n\n"
            "In addition to encryption, HTTPS also authenticates the identity of the website, ensuring that users are actually communicating with the intended website and not an imposter. This is achieved through the use of digital certificates issued by trusted Certificate Authorities (CAs). When a website uses HTTPS, the website's digital certificate verifies its identity and ensures that users are not being misled by counterfeit websites. \n\n"
            "Another essential aspect of secure browsing is avoiding phishing attacks, which are deceptive attempts by cybercriminals to trick users into revealing their personal information. Phishing attacks often come in the form of fraudulent emails, fake websites, or pop-up messages that look legitimate but are designed to steal login credentials, financial information, or other sensitive data. Secure browsing practices involve being vigilant and cautious when interacting with links, attachments, or requests for personal information. \n\n"
            "To further enhance secure browsing, users can take several additional precautions. First, using strong, unique passwords for different websites is essential to prevent unauthorized access. Many websites now offer multi-factor authentication (MFA), which adds an extra layer of security by requiring a second form of verification, such as a text message or authentication app, in addition to a password. \n\n"
            "Secondly, ensuring that the browser and all installed plugins or extensions are kept up to date is crucial for secure browsing. Browser vendors regularly release security updates that address vulnerabilities, so keeping browsers up to date reduces the risk of exposure to known threats. Outdated browser versions may have vulnerabilities that attackers can exploit to gain access to sensitive information. \n\n"
            "Using secure browsing practices also involves being cautious when visiting websites. Avoiding suspicious websites and links, especially from untrusted sources, can prevent exposure to malware, ransomware, and other types of malicious software. Additionally, it's important to be mindful of the personal information shared online. The less personal data shared on a website, the less there is for attackers to exploit. \n\n"
            "Another important aspect of secure browsing is utilizing a Virtual Private Network (VPN) when browsing on public Wi-Fi networks. A VPN encrypts all of the user's internet traffic and routes it through a secure server, making it difficult for third parties to intercept or monitor the user's online activities. This is particularly useful when using unprotected public networks, which are often targeted by cybercriminals looking to steal personal information. \n\n"
            "While HTTPS is an important part of secure browsing, it is not the only layer of protection needed. For a truly secure browsing experience, users must also adopt a combination of good security habits, such as being aware of the risks of phishing, using secure passwords, keeping software up to date, and avoiding risky websites and content. \n\n"
            "In conclusion, secure browsing is essential for protecting personal information and maintaining privacy in the digital age. By using HTTPS, being cautious of phishing attacks, utilizing strong passwords, keeping software updated, and using a VPN when on public networks, users can significantly reduce their exposure to online threats. Staying vigilant and adopting these best practices can help users safeguard their online activities and keep their data secure from cybercriminals. ",
          videoId: 'j9QmMEWmcfo',
        ),
        '/quiz/phishing': (context) => QuizScreen(topic: 'Phishing'),
        '/quiz/password_management': (context) => QuizScreen(topic: 'Password Management'),
        '/quiz/malware': (context) => QuizScreen(topic: 'Malware'),
        '/quiz/social_engineering': (context) => QuizScreen(topic: 'Social Engineering'),
        '/quiz/secure_browsing_and_https': (context) => QuizScreen(topic: 'Secure Browsing and HTTPS'),

        '/topic/cryptography': (context) => InterDetailScreen(
          title: "Cryptography",
          article:
            "Cryptography is the science and practice of securing communication and data through the use of mathematical algorithms, ensuring that information remains confidential, authentic, and tamper-proof. It is a cornerstone of modern security systems and plays a vital role in protecting sensitive information from unauthorized access. Cryptography ensures that data, whether stored or transmitted, remains secure from adversaries seeking to compromise its confidentiality or integrity.\n\n"
            "At its core, cryptography involves two main processes: encryption and decryption. Encryption is the process of transforming readable data, known as plaintext, into an unreadable format, called ciphertext, using a specific algorithm and a key. This ensures that even if someone intercepts the data, they cannot read it without the correct key to decrypt it. Decryption, on the other hand, is the reverse process, where ciphertext is converted back into its original plaintext form using the correct key.\n\n"
            "One of the most well-known applications of cryptography is symmetric encryption, where the same key is used for both encryption and decryption. This method is efficient but has the challenge of securely distributing the key to both parties. Asymmetric encryption, also known as public-key cryptography, overcomes this issue by using a pair of keys: a public key for encryption and a private key for decryption. This allows for secure communication even if the encryption key is known to everyone, as only the recipient with the corresponding private key can decrypt the message.\n\n"
            "Cryptography also includes digital signatures, which are used to verify the authenticity and integrity of a message or document. A digital signature is a mathematical scheme for verifying the integrity and origin of data. It ensures that the data has not been tampered with and that the sender is who they claim to be. Digital signatures are commonly used in applications such as software distribution, financial transactions, and legal agreements to provide non-repudiation, meaning that the sender cannot deny sending the message.\n\n"
            "Hashing is another critical aspect of cryptography. A hash function takes an input (or 'message') and returns a fixed-size string of bytes, typically a hash value, which appears random. This value is unique to the input data, meaning even a small change in the input results in a completely different hash. Hashing is used to store passwords securely, verify the integrity of files, and ensure that data has not been altered during transmission. Unlike encryption, hashing is a one-way process, meaning that the original data cannot be retrieved from the hash.\n\n"
            "Key exchange protocols are another essential component of cryptography. These protocols allow two parties to securely exchange cryptographic keys over an untrusted network. One of the most widely used key exchange algorithms is the Diffie-Hellman key exchange, which enables two parties to share a secret key that can be used for encryption, without directly transmitting the key itself. This ensures that even if an attacker intercepts the key exchange, they cannot deduce the secret key.\n\n"
            "Modern cryptography is indispensable in a variety of applications, especially in the digital age where the protection of personal and financial information is a top priority. Cryptographic techniques secure online transactions, communications, and data storage across many industries, including banking, e-commerce, healthcare, and government services. For example, when you make an online purchase, cryptographic methods like SSL/TLS encryption are used to protect your credit card information during transmission, ensuring that hackers cannot steal your sensitive data.\n\n"
            "Cryptography is also a vital tool in securing communication channels, such as email and instant messaging. Encryption ensures that only the sender and recipient can read the message, preventing eavesdropping by third parties. Secure communication protocols like PGP (Pretty Good Privacy) and end-to-end encryption services are widely used to ensure private communication in the face of rising cyber threats.\n\n"
            "In addition to protecting individual privacy, cryptography plays a crucial role in securing entire systems, including cybersecurity infrastructure, cloud storage, and digital identity verification. Technologies like blockchain, which underpins cryptocurrencies like Bitcoin, rely on cryptographic algorithms to maintain secure and immutable records. This decentralized approach to secure data storage ensures that no single entity has control over the information, offering increased transparency and trust.\n\n"
            "However, as cryptographic methods evolve, so do the techniques used by cybercriminals to attack them. Researchers and security experts must continually assess the strength and vulnerabilities of cryptographic algorithms to ensure they remain secure in the face of emerging technologies, such as quantum computing. Quantum computers have the potential to break certain types of cryptography, leading to a new wave of cryptographic research focused on developing algorithms resistant to quantum attacks.\n\n"
            "In conclusion, cryptography is a cornerstone of modern cybersecurity, providing the tools necessary to protect sensitive data from unauthorized access, tampering, and fraud. By utilizing encryption, decryption, digital signatures, hashing, and key exchange protocols, cryptography ensures the confidentiality, authenticity, and integrity of data in a world that increasingly relies on digital communication. As technology continues to advance, cryptography will remain an essential field, safeguarding the privacy and security of individuals and organizations alike.",
          videoId: 'trHox1bN5es',
        ),

        '/topic/network_security': (context) => InterDetailScreen(
          title: "Network Security",
          article:
            "Network security refers to the measures, technologies, and practices designed to protect the integrity, confidentiality, and availability of data and resources as they are transmitted across or accessed through a network. In an increasingly connected world, network security is vital to ensuring that sensitive information remains safe from unauthorized access, cyberattacks, and data breaches. As networks grow in complexity, so too do the threats that target them, making network security an essential aspect of modern cybersecurity.\n\n"
            "Effective network security involves implementing a variety of hardware and software solutions to defend against malicious activity. One of the most fundamental tools in network security is the firewall, which acts as a barrier between a trusted internal network and untrusted external networks, such as the internet. Firewalls can filter incoming and outgoing traffic based on predefined security rules, blocking unauthorized access and preventing potential attacks from entering the network.\n\n"
            "Another crucial component of network security is intrusion detection and prevention systems (IDS/IPS). These systems monitor network traffic for signs of suspicious activity and attempt to detect potential threats, such as malware, unauthorized access attempts, or denial-of-service (DoS) attacks. IDS systems alert administrators when a potential threat is detected, while IPS systems go a step further by automatically taking action to block or mitigate the attack. Both IDS and IPS play an essential role in identifying and responding to threats in real time.\n\n"
            "Virtual Private Networks (VPNs) are another key tool in network security, especially for businesses and individuals working remotely. VPNs create a secure, encrypted connection between a device and a remote server, allowing users to access network resources as though they were physically connected to the local network. This encrypted tunnel ensures that data transmitted over public networks is protected from eavesdropping, preventing attackers from intercepting sensitive information.\n\n"
            "Encryption, both at rest and in transit, is also a vital element of network security. When data is encrypted, it is transformed into an unreadable format that can only be decrypted with a specific key. This protects the data from unauthorized access, even if it is intercepted during transmission. For example, SSL/TLS encryption is used to secure web traffic, ensuring that sensitive information like passwords, credit card numbers, and personal details remain protected during online transactions.\n\n"
            "In addition to these technical solutions, network security also involves strategic measures like segmentation and access control. Network segmentation involves dividing a network into smaller, isolated sub-networks to limit the spread of potential attacks. By segmenting the network, organizations can contain breaches to a specific section, minimizing damage and making it easier to monitor and manage security.\n\n"
            "Access control is another essential strategy in network security. It involves defining who can access specific network resources and ensuring that only authorized users and devices are granted access. This can be achieved through authentication mechanisms like usernames and passwords, as well as more advanced methods such as biometric identification or multi-factor authentication (MFA). Access control policies should be enforced based on the principle of least privilege, meaning that users and devices are granted the minimum level of access required to perform their tasks.\n\n"
            "Monitoring network traffic is also crucial for detecting and responding to suspicious activity. By continuously monitoring the flow of data across the network, organizations can identify abnormal patterns that may indicate a cyberattack, such as unusual traffic spikes or the presence of malware. Real-time monitoring tools can provide alerts to security personnel, enabling them to take immediate action to mitigate the threat and prevent further damage.\n\n"
            "The goal of network security is to ensure that only legitimate users and devices can access network resources while preventing malicious activities that could compromise network operations and sensitive information. Effective network security requires a multi-layered approach, combining the use of hardware and software tools with strong organizational policies and user training to safeguard against a wide range of threats.\n\n"
            "In conclusion, network security is a critical aspect of maintaining the integrity and confidentiality of data in a connected world. By implementing firewalls, intrusion detection and prevention systems, VPNs, encryption, and access control, organizations can defend their networks from a variety of cyber threats. Ongoing monitoring and real-time response to suspicious activity are also key components of a robust network security strategy. Ultimately, a proactive and comprehensive approach to network security can help organizations protect their data and maintain the trust of their users and customers.",
          videoId: 'rG02r5y2Fdo',
        ),

        '/topic/incident_response': (context) => InterDetailScreen(
          title: "Incident Response",
          article:
            "Incident response in cybersecurity refers to the systematic approach organizations take to prepare for, detect, contain, mitigate, and recover from security incidents or cyberattacks. In the ever-evolving landscape of cyber threats, having a well-defined and effective incident response process is essential for minimizing damage and ensuring a swift recovery. Organizations that are well-prepared to handle security incidents are more likely to reduce downtime and prevent further damage.\n\n"
            "The first phase of an incident response plan is **preparation**, which involves creating policies, establishing a response team, and training staff. The preparation phase is crucial because it ensures that the organization has the necessary resources, knowledge, and procedures in place to handle incidents efficiently. During this phase, organizations develop incident response plans, conduct tabletop exercises, and implement security measures such as firewalls, intrusion detection systems, and data encryption. The preparation phase is all about ensuring that the organization is ready to respond when an incident occurs.\n\n"
            "The second phase is **detection**, where the goal is to identify potential security incidents. This phase involves monitoring systems and networks for signs of suspicious activity or anomalies that could indicate an attack. Detection can be accomplished through tools like intrusion detection systems (IDS), security information and event management (SIEM) systems, and network traffic analysis. Quick detection is critical for minimizing the impact of an incident, as it allows the response team to act swiftly and contain the attack before it spreads further.\n\n"
            "Once an incident is detected, the next phase is **containment**. The containment phase involves isolating the affected systems to prevent the attack from spreading to other parts of the network or systems. Containment strategies vary depending on the nature of the incident. For example, if a malware infection is detected, the infected machines might be disconnected from the network to stop the malware from communicating with external servers. The goal of containment is to limit the scope of the attack and reduce further damage while allowing the response team to analyze the situation.\n\n"
            "After containment, the **eradication** phase begins. This phase focuses on removing the threats that caused the security incident. For instance, if malware was identified in the containment phase, the eradication process would involve completely removing the malware from affected systems and ensuring that all traces of the threat are eliminated. Eradication may also involve patching vulnerabilities or changing passwords to prevent the attacker from regaining access. This phase ensures that the threat is fully neutralized and that no residual risks remain.\n\n"
            "The **recovery** phase follows eradication and is focused on restoring normal operations. During this phase, the response team works to bring affected systems back online while ensuring that they are secure and free from threats. This may involve restoring data from backups, rebuilding systems, or reinstalling software. The recovery process should be done gradually to ensure that systems are thoroughly tested for vulnerabilities before being fully restored. The goal is to return to normal business operations as quickly as possible while minimizing the risk of further incidents.\n\n"
            "Finally, the **lessons learned** phase is an essential part of the incident response process. After the incident has been resolved, the response team conducts a post-incident analysis to identify what went well, what could have been improved, and how the organization can better prepare for future incidents. This phase often includes a detailed review of the response, an analysis of the root cause of the incident, and the implementation of improvements to the incident response plan. Lessons learned help organizations refine their security posture, better understand emerging threats, and improve their overall cybersecurity resilience.\n\n"
            "An effective incident response plan is crucial for minimizing the impact of cyberattacks and ensuring business continuity. By preparing for incidents, detecting threats early, containing attacks, eradicating threats, recovering quickly, and learning from past events, organizations can strengthen their security posture and reduce the likelihood of future incidents. In today’s world, where cyberattacks are increasingly sophisticated and frequent, having a comprehensive incident response strategy is essential to protecting an organization’s data, reputation, and operations.\n\n"
            "In conclusion, incident response is a vital aspect of cybersecurity that ensures organizations can handle security incidents in a structured and efficient manner. A robust incident response plan can significantly reduce the damage caused by cyberattacks, help maintain business continuity, and improve an organization’s overall cybersecurity strategy. By continuously refining their response processes and learning from previous incidents, organizations can stay ahead of evolving threats and better protect their critical assets.",
          videoId: 'IRSQEO0koYY',
        ),

        '/topic/access_control': (context) => InterDetailScreen(
          title: "Access Control",
          article:
            "Access control in cybersecurity refers to the policies, mechanisms, and processes used to restrict and manage access to systems, networks, or data based on the identity of users and their assigned permissions. It is a fundamental aspect of protecting sensitive information and resources from unauthorized access, ensuring that only individuals or entities with the proper authorization can interact with critical systems. Access control is essential for maintaining the confidentiality, integrity, and availability of data and resources within an organization.\n\n"
            "Access control can be implemented using a variety of models, each designed to cater to different security needs and organizational structures. Three of the most commonly used access control models are **Discretionary Access Control (DAC)**, **Mandatory Access Control (MAC)**, and **Role-Based Access Control (RBAC)**. Each of these models provides a unique approach to determining who can access what resources and under what conditions.\n\n"
            "**Discretionary Access Control (DAC)** is one of the most flexible models, where the owner of the resource has the discretion to determine who can access it. In this model, the resource owner has the authority to assign permissions to other users, granting them the ability to read, write, or execute specific files or systems. While DAC offers flexibility, it also poses potential risks, as the owner might inadvertently grant overly permissive access to sensitive data, leading to security vulnerabilities.\n\n"
            "**Mandatory Access Control (MAC)**, on the other hand, is a more restrictive model, where access decisions are not made by resource owners but rather enforced through strict policies established by system administrators. In MAC, access to resources is based on security labels or classifications that dictate how data and resources are accessed. For example, in a military environment, MAC may involve security levels such as ‘Top Secret’, ‘Secret’, and ‘Confidential’. MAC ensures that users can only access information that is deemed appropriate based on their clearance level, helping to minimize the risk of data leaks or unauthorized access.\n\n"
            "**Role-Based Access Control (RBAC)** is a widely used model in organizations where access to resources is based on a user’s role within the organization. In RBAC, permissions are assigned to specific roles, and users are granted access based on their assigned role. For example, an employee in the finance department might have access to financial records, while a marketing employee may only have access to marketing materials. This model helps simplify the management of access permissions, especially in large organizations, and ensures that employees only have access to the resources necessary for their job responsibilities.\n\n"
            "In addition to these access control models, effective access control systems are often built on the principle of least privilege. This principle dictates that users should only be granted the minimum level of access necessary to perform their job functions. By limiting access to sensitive data and systems, organizations can reduce the risk of insider threats, data breaches, and unauthorized actions. The principle of least privilege also helps mitigate the damage caused by compromised accounts, as attackers would be limited in their ability to access or exfiltrate sensitive resources.\n\n"
            "Access control systems also incorporate authentication and authorization mechanisms to ensure that users are who they claim to be and that they have the appropriate permissions to access resources. Authentication typically involves verifying a user’s identity using methods such as passwords, biometrics, or multi-factor authentication (MFA), while authorization involves granting or denying access based on the user’s credentials and permissions.\n\n"
            "To further enhance security, many organizations implement continuous monitoring and auditing of access control systems. This allows organizations to track who accessed what resources and when, providing valuable insights into potential security threats and ensuring compliance with regulations. Regular auditing also helps identify misconfigurations or vulnerabilities in the access control system that could lead to unauthorized access.\n\n"
            "In conclusion, access control plays a crucial role in cybersecurity by ensuring that only authorized individuals or entities can access sensitive data and systems. By implementing effective access control models, such as DAC, MAC, and RBAC, organizations can better protect their resources and enforce the principle of least privilege. A strong access control strategy, combined with robust authentication and authorization mechanisms, can significantly reduce the risk of unauthorized access and data breaches, ultimately strengthening the overall security posture of an organization.",
          videoId: '747tbiV0wCk',
        ),

        '/topic/security_testing': (context) => InterDetailScreen(
        title: "Security Testing",
        article:
          "Security testing is the process of evaluating an application, network, or system to identify vulnerabilities, weaknesses, and potential threats that could be exploited by attackers. It is a crucial part of the software development lifecycle and IT infrastructure maintenance, as it helps to ensure that systems are resistant to unauthorized access and exploitation. By identifying vulnerabilities before they can be exploited, organizations can proactively address security issues and strengthen their defenses against cyberattacks.\n\n"
          "The primary goal of security testing is to assess the effectiveness of security controls in place, maintain data integrity, and protect sensitive information from unauthorized access, modification, or disclosure. Security controls such as encryption, authentication mechanisms, and firewalls are designed to protect data from threats, and security testing evaluates whether these controls are functioning as intended. The process is essential for safeguarding personal, financial, and confidential business information, ensuring that data remains private and secure.\n\n"
          "Security testing encompasses a wide range of techniques and tests, with the most common being **vulnerability scanning**, **penetration testing**, and **security auditing**. Vulnerability scanning involves using automated tools to identify known vulnerabilities in software and systems. These tools compare the system against a database of known flaws and report any issues that may require patching. While vulnerability scanning is effective at spotting known issues, it cannot identify unknown vulnerabilities or those that are specific to a particular environment.\n\n"
          "**Penetration testing**, also known as ethical hacking, is a more in-depth form of security testing. In this process, security professionals simulate real-world cyberattacks to assess how well a system can withstand an attack. Penetration testers use various techniques to identify vulnerabilities and exploit them, attempting to gain unauthorized access to the system. The results of penetration tests help organizations understand the potential damage an attacker could cause and guide them in strengthening weak points in their defenses.\n\n"
          "**Security auditing** involves reviewing an organization's security policies, procedures, and configurations to ensure they are in line with best practices and security standards. Auditing may include reviewing access control settings, system configurations, and the effectiveness of security measures in place. Security audits can also help organizations maintain compliance with regulatory requirements such as HIPAA, GDPR, or PCI-DSS, which mandate specific security measures to protect sensitive data.\n\n"
          "Some common issues that security testing looks for include **authentication flaws**, **encryption weaknesses**, and exposure to common vulnerabilities like **SQL injection**, **cross-site scripting (XSS)**, and **buffer overflow attacks**. **Authentication flaws** occur when systems fail to properly verify the identity of users, potentially allowing unauthorized access. **Encryption weaknesses** can leave data exposed to attackers if sensitive information is transmitted or stored without adequate protection.\n\n"
          "**SQL injection** is a vulnerability that allows attackers to manipulate a system’s database by injecting malicious SQL code into input fields. It can lead to unauthorized access to or manipulation of a system's data. **Cross-site scripting (XSS)** is a vulnerability that allows attackers to inject malicious scripts into web applications, which can be executed in a user's browser and steal sensitive information, such as session tokens or login credentials. **Buffer overflow attacks** occur when more data is written to a buffer than it can handle, causing it to overwrite adjacent memory locations, often leading to system crashes or unauthorized code execution.\n\n"
          "Security testing also includes examining a system's defenses against other cyberattacks, such as **Denial of Service (DoS)** attacks, **man-in-the-middle (MITM) attacks**, and **privilege escalation**. **Denial of Service attacks** overwhelm a system’s resources, rendering it inaccessible to legitimate users. **MITM attacks** occur when an attacker intercepts communication between two parties and potentially alters or steals information. **Privilege escalation** happens when an attacker gains elevated access to a system, allowing them to execute unauthorized actions with higher privileges.\n\n"
          "By conducting regular security testing, organizations can identify weaknesses in their systems and address them before attackers can exploit them. Security testing helps organizations maintain compliance with industry standards, improve their security posture, and minimize the risk of data breaches and other cyberattacks. As the threat landscape continues to evolve, security testing remains an essential tool in the fight to protect sensitive data and maintain the integrity of systems.\n\n"
          "In conclusion, security testing plays a vital role in maintaining the security and integrity of systems, applications, and networks. By identifying vulnerabilities, weaknesses, and potential threats, organizations can ensure that they are prepared to defend against cyberattacks. Implementing a comprehensive security testing strategy helps prevent data breaches, safeguard sensitive information, and build trust with customers and stakeholders.",
          videoId: 'VvUw-wZWvbc',
        ),
        '/quiz/cryptography': (context) => InterQuizScreen(topic: 'Cryptography'),
        '/quiz/network_security': (context) => InterQuizScreen(topic: 'Network Security'),
        '/quiz/incident_response': (context) => InterQuizScreen(topic: 'Incident Response'),
        '/quiz/access_control': (context) => InterQuizScreen(topic: 'Access Control'),
        '/quiz/security_testing': (context) => InterQuizScreen(topic: 'Security Testing'),

        '/topic/advanced_cryptography': (context) => AdvanceDetailScreen(
          title: "Advanced Cryptography",
          article:
            "Advanced cryptography involves complex techniques and algorithms designed to enhance the security and privacy of data in modern computing systems. As technology evolves and computational power increases, traditional cryptographic methods need to be supplemented with advanced techniques to meet the growing demands of cybersecurity. Advanced cryptographic methods ensure the confidentiality, integrity, and authenticity of sensitive information, protecting it against increasingly sophisticated attacks.\n\n"
            "One of the key advanced cryptographic techniques is **Elliptic Curve Cryptography (ECC)**. ECC is a public-key encryption system that offers a higher level of security with shorter key lengths compared to traditional methods such as RSA. By using the mathematical properties of elliptic curves over finite fields, ECC provides efficient encryption, making it well-suited for environments with constrained resources, such as mobile devices and IoT devices. Its popularity is growing in modern security protocols, including secure web browsing (TLS/SSL) and cryptocurrency systems like Bitcoin.\n\n"
            "Another important development in cryptography is the rise of **quantum-resistant algorithms**. As quantum computing progresses, there is increasing concern that it could break current cryptographic standards, such as RSA and ECC, which rely on the difficulty of factoring large numbers and solving discrete logarithms. Quantum computers, with their ability to process vast amounts of data simultaneously, could potentially crack these encryption schemes in a matter of seconds. Quantum-resistant algorithms are being developed to provide encryption methods that are secure even in the presence of quantum computers. Post-quantum cryptography (PQC) focuses on creating new algorithms that rely on problems that are difficult for both classical and quantum computers to solve, ensuring long-term data security.\n\n"
            "**Homomorphic encryption** is another advanced technique that enables computations to be performed on encrypted data without decrypting it. This allows data to remain private even while being processed, which is crucial for applications like cloud computing, where sensitive data is often stored and processed by third-party providers. Homomorphic encryption ensures that the computation results are correct and that the data privacy is maintained throughout the process. This technique holds great potential for secure outsourcing of computations while preserving the confidentiality of the data involved.\n\n"
            "**Zero-knowledge proofs (ZKPs)** are another advanced cryptographic method that allows one party to prove to another party that a statement is true, without revealing any additional information. ZKPs are widely used in blockchain and cryptocurrency systems, providing a way to verify transactions or identities without exposing sensitive data. This makes ZKPs an essential tool for enhancing privacy in decentralized systems, as they allow users to prove their actions or ownership of assets without revealing personal details. ZKPs can be classified into interactive and non-interactive types, with non-interactive ZKPs becoming more popular due to their efficiency.\n\n"
            "In addition to these techniques, advanced cryptography plays a critical role in securing **cloud security** and **blockchain** systems. In cloud computing, organizations often store sensitive data with third-party providers, creating a need for strong encryption methods that ensure data is kept private and secure. Advanced cryptographic methods like homomorphic encryption and secure multi-party computation (SMPC) allow computations to occur without revealing the underlying data, addressing privacy concerns in cloud-based environments.\n\n"
            "**Blockchain** technology, which underpins cryptocurrencies like Bitcoin and Ethereum, also relies heavily on cryptographic principles. Cryptography ensures the integrity of transactions and the immutability of the blockchain, providing trust in decentralized networks. Blockchain's reliance on cryptography to secure transactions, validate identities, and ensure consensus among network participants makes it one of the most promising technologies for secure and transparent systems.\n\n"
            "Looking ahead, the potential impact of quantum computing on existing cryptographic standards is one of the biggest challenges for cryptography experts. As quantum computers become more powerful, they could potentially break many of the encryption algorithms currently used in digital security. This has led to intense research into quantum-resistant algorithms, which are being developed to ensure data security in the post-quantum era.\n\n"
            "In conclusion, advanced cryptography is a crucial component of modern cybersecurity. With the rise of quantum computing, cloud-based services, and decentralized systems, traditional cryptographic techniques alone are no longer sufficient. Techniques such as elliptic curve cryptography, quantum-resistant algorithms, homomorphic encryption, and zero-knowledge proofs are at the forefront of securing data and communications in an increasingly complex digital landscape. As the field of cryptography continues to evolve, these advanced techniques will play a key role in addressing emerging security challenges and ensuring privacy and trust in the digital age.",
          videoId: 'WzXvVZHT7nQ',
        ),

        '/topic/penetration_testing': (context) => AdvanceDetailScreen(
          title: "Penetration Testing",
          article:
          "Penetration testing, also known as ethical hacking, is a proactive security practice where authorized professionals simulate real-world cyberattacks on a system, network, or application to identify vulnerabilities and weaknesses that could be exploited by malicious hackers. This method helps organizations discover potential security flaws before they can be leveraged by cybercriminals. By mimicking the tactics, techniques, and procedures (TTPs) used by attackers, penetration testers can provide valuable insights into how well an organization's security defenses can withstand an attack.\n\n"
          "The primary goal of penetration testing is to assess the security of systems and identify vulnerabilities that could lead to unauthorized access, data breaches, or disruption of services. Penetration testers, also known as ethical hackers, attempt to exploit security weaknesses by using the same tools and techniques as malicious hackers, but with the permission and oversight of the organization being tested. By simulating real-world attack scenarios, penetration testing helps businesses understand their risk exposure and strengthens their defenses against cyber threats.\n\n"
          "Penetration testing involves several key phases, starting with **planning and scoping**. During this phase, the testing team works with the organization to define the scope of the test, the systems and networks to be tested, and the goals of the penetration test. This ensures that the ethical hackers focus their efforts on critical assets and align their activities with the organization’s priorities.\n\n"
          "The next phase is **information gathering**, where penetration testers collect data about the target system. This can include scanning for open ports, identifying software versions, and mapping the network topology. Information gathering is crucial for understanding the potential attack surface and helps identify possible entry points for exploitation.\n\n"
          "Once the information gathering is complete, penetration testers move on to the **vulnerability analysis** phase. In this phase, they identify known vulnerabilities in the system, such as outdated software, misconfigured servers, or weak password policies. This analysis is often assisted by automated vulnerability scanning tools, although manual verification is also performed to ensure accuracy.\n\n"
          "The **exploitation** phase is where ethical hackers attempt to take advantage of identified vulnerabilities. This may involve exploiting weaknesses such as SQL injection, cross-site scripting (XSS), or buffer overflow vulnerabilities to gain unauthorized access or escalate privileges within the system. The goal here is to determine the extent to which an attacker can penetrate the system, and to understand the potential impact of such an attack.\n\n"
          "After successful exploitation, penetration testers move into the **post-exploitation** phase, where they assess the potential consequences of the breach. This includes determining whether an attacker could access sensitive data, move laterally within the network, or cause significant damage. Testers may also evaluate the persistence of the exploit, such as the ability to maintain access or escalate privileges over time.\n\n"
          "Finally, the **reporting** phase involves documenting the findings and providing actionable recommendations to improve security. This report details the vulnerabilities discovered, the methods used to exploit them, and the potential impact of an attack. Penetration testers also provide remediation strategies, which may include patching vulnerabilities, tightening access controls, and improving employee awareness through training.\n\n"
          "Penetration testing is essential for organizations that want to proactively identify and address security gaps. By uncovering vulnerabilities before they are exploited by real attackers, businesses can mitigate risks, strengthen their defenses, and improve their overall security posture. Penetration tests also help ensure compliance with regulatory standards, such as PCI-DSS, HIPAA, and GDPR, which often require regular security assessments.\n\n"
          "In conclusion, penetration testing is a critical component of any comprehensive cybersecurity strategy. It provides organizations with the opportunity to identify weaknesses, understand their risk exposure, and implement corrective actions before an actual cyberattack occurs. Whether testing network infrastructure, web applications, or employee awareness, penetration testing offers actionable insights to enhance security and protect sensitive information from cyber threats.",
          videoId: 'qEBZc0oxCDM',
        ),

        '/topic/ids': (context) => AdvanceDetailScreen(
          title: "Intrusion Detection Systems (IDS)",
          article:
            "Intrusion Detection Systems (IDS) are security solutions designed to monitor network traffic or system activities for signs of malicious behavior, policy violations, or unauthorized access. IDS systems help organizations detect potential security breaches in real time, enabling administrators to take immediate action to prevent or mitigate damage. IDS are an essential component of a comprehensive cybersecurity strategy, as they help safeguard sensitive data, maintain system integrity, and ensure business continuity.\n\n"
            "IDS can be classified into two main types: **Network-based IDS (NIDS)** and **Host-based IDS (HIDS)**. The primary difference between the two lies in where they operate and what they monitor. **Network-based IDS (NIDS)** monitors network traffic for suspicious patterns, such as unusual communication between devices, unauthorized data flows, or known attack signatures. NIDS analyzes network packets to identify potential threats, such as denial-of-service (DoS) attacks, port scanning, or malware propagation. By observing the entire network's traffic, NIDS can provide insights into attack attempts targeting multiple devices or systems simultaneously.\n\n"
            "On the other hand, **Host-based IDS (HIDS)** operates on individual devices or hosts within a network. It analyzes system activities, logs, and configurations to detect any signs of intrusion on that particular host. HIDS can monitor processes, file changes, user activities, and network connections, and can be especially useful in detecting attacks that target specific systems. For instance, HIDS can detect when an attacker tries to exploit a vulnerability on a specific server or gain unauthorized access to sensitive files. Unlike NIDS, which analyzes traffic across a network, HIDS provides a more detailed view of activities on a single host.\n\n"
            "IDS work by detecting anomalies, known attack signatures, or behavior deviations from established baselines. **Signature-based IDS** uses a database of predefined attack patterns or signatures to identify known threats. It compares incoming traffic or system activity against this database and raises alerts when a match is found. Signature-based detection is effective at identifying known attack vectors, such as malware or specific exploits, but it may struggle to detect new or unknown threats that don't match any signatures in the database.\n\n"
            "On the other hand, **Anomaly-based IDS** uses machine learning or statistical methods to establish a baseline of normal system or network behavior. Any deviation from this baseline is flagged as a potential anomaly or threat. Anomaly-based IDS can be more effective at detecting novel or previously unknown attacks, as they do not rely on predefined signatures. However, anomaly-based IDS may generate more false positives, as benign activities that deviate from the norm could also be flagged as suspicious.\n\n"
            "Another key component of IDS is **behavioral analysis**, which looks at patterns of activity rather than specific signatures. This type of analysis identifies abnormal behavior that may indicate malicious actions, even if the exact attack signature is unknown. For example, an attacker attempting to escalate privileges or move laterally within a network may not trigger a signature-based IDS but could be detected by a behavioral IDS due to abnormal actions such as unusual login times or access patterns.\n\n"
            "Once an intrusion is detected, IDS raises alerts to notify system administrators of potential security incidents. These alerts can be used to initiate further investigation or mitigation actions, such as isolating affected systems, blocking malicious IP addresses, or implementing firewall rules. While IDS systems provide valuable detection capabilities, they generally do not take automated action to block attacks. Some systems, however, integrate with other security solutions like **Intrusion Prevention Systems (IPS)** to automatically respond to detected threats.\n\n"
            "IDS systems are critical in defending against a wide range of cyber threats, including malware, insider threats, advanced persistent threats (APTs), and denial-of-service attacks. By providing real-time monitoring and alerting, IDS allows security teams to respond quickly to incidents and prevent further damage. They also provide valuable data for forensic analysis, helping organizations understand the nature of an attack and improve their security posture in the future.\n\n"
            "In conclusion, Intrusion Detection Systems (IDS) are an essential part of network and system security. Whether network-based or host-based, IDS are designed to detect potential intrusions by analyzing system activities and network traffic for suspicious behavior. By identifying known attack signatures, anomalies, and behavioral deviations, IDS help organizations proactively defend against cyber threats, mitigate risks, and strengthen overall security. With the increasing sophistication of cyberattacks, deploying IDS is critical to maintaining a strong cybersecurity framework and ensuring the safety of sensitive data.",
          videoId: 'R1mF7Mxfynk',
        ),

        '/topic/cloud_security': (context) => AdvanceDetailScreen(
          title: "Cloud Security",
          article:
            "Cloud security refers to the set of practices, technologies, and policies designed to protect data, applications, and services that are hosted in cloud environments. With the rapid adoption of cloud computing, ensuring the security of cloud-based infrastructure has become a top priority for businesses and organizations worldwide. Cloud security encompasses a broad spectrum of security measures aimed at protecting cloud services from cyber threats, data breaches, and unauthorized access, while also ensuring compliance with relevant regulations.\n\n"
            "One of the foundational aspects of cloud security is **data encryption**. Cloud providers typically offer encryption for data at rest (stored data) and data in transit (data being transferred). Encryption ensures that even if data is intercepted or accessed by unauthorized parties, it remains unreadable without the decryption key. This is crucial for safeguarding sensitive information, such as personal data, financial details, and intellectual property, in the cloud environment. Encryption protects data across various cloud platforms, including public, private, and hybrid clouds, enhancing privacy and security.\n\n"
            "Another critical aspect of cloud security is **access control**. Organizations must ensure that only authorized individuals can access specific cloud resources. This is often achieved through a combination of **Identity and Access Management (IAM)** systems, which enforce strict authentication and authorization protocols. IAM helps organizations control who can access their data and applications in the cloud, based on user roles and permissions. By defining user roles, organizations can enforce the principle of least privilege, ensuring that users have only the access they need to perform their job functions, reducing the risk of accidental or malicious data exposure.\n\n"
            "**Multi-factor authentication (MFA)** is another key component of cloud security. MFA adds an additional layer of protection by requiring users to provide multiple forms of verification, such as a password and a unique code sent to their mobile device, before they can access cloud services. This significantly reduces the likelihood of unauthorized access, even if a user’s credentials are compromised. MFA is becoming an essential security measure for cloud services, as it helps mitigate the risks associated with password theft and phishing attacks.\n\n"
            "Given the distributed nature of cloud environments, **threat detection** plays a vital role in identifying and responding to potential security incidents. Cloud providers typically offer a range of tools and services that help businesses monitor their cloud infrastructure for signs of suspicious activity or breaches. These tools use advanced machine learning, behavioral analytics, and threat intelligence to detect anomalies and alert administrators in real time. Additionally, organizations can implement their own monitoring solutions to complement cloud provider tools, creating a more robust defense against cyber threats.\n\n"
            "The **shared responsibility model** is a key concept in cloud security. Under this model, the cloud provider is responsible for securing the cloud infrastructure, including physical data centers, hardware, and networking components. However, customers are responsible for securing their data, applications, and access controls within the cloud environment. This division of responsibility requires clear communication and collaboration between the provider and customer to ensure that both parties effectively manage risks. Cloud security ensures that the provider and customer work together to protect sensitive data while leveraging the scalability and flexibility of cloud services.\n\n"
            "Compliance with privacy regulations is another important aspect of cloud security. Organizations must ensure that their cloud services comply with industry-specific regulations and standards, such as the **General Data Protection Regulation (GDPR)**, **Health Insurance Portability and Accountability Act (HIPAA)**, and **Payment Card Industry Data Security Standard (PCI-DSS)**. Cloud providers typically offer certifications and audits to demonstrate their compliance with these regulations, helping customers maintain their own compliance obligations. Ensuring compliance with these regulations is critical for avoiding legal penalties and maintaining customer trust.\n\n"
            "Cloud security also involves maintaining **data integrity**, ensuring that data is accurate, consistent, and reliable throughout its lifecycle. Cloud providers implement a variety of techniques, such as redundancy, backup, and integrity checks, to protect data from corruption or loss. These measures ensure that businesses can continue operations even in the event of a hardware failure or cyberattack, preventing data loss or downtime that could disrupt services or damage reputation.\n\n"
            "In conclusion, cloud security is a critical component of modern cybersecurity strategies, protecting sensitive data and applications hosted in the cloud. By implementing robust security measures such as encryption, access control, multi-factor authentication, and threat detection, organizations can secure their cloud environments against cyber threats and unauthorized access. The shared responsibility model ensures that both cloud providers and customers collaborate to manage risks, while compliance with privacy regulations ensures that data is handled responsibly. As businesses continue to adopt cloud services, investing in cloud security is essential for maintaining privacy, integrity, and trust in the digital age.",
          videoId: 'jI8IKpjiCSM',
        ),

        '/topic/zero_trust': (context) =>AdvanceDetailScreen(
          title: "Zero Trust Architecture",
          article:
            "Zero Trust Architecture (ZTA) is a security framework based on the principle that no entity, whether inside or outside an organization's network, should be trusted by default. This model challenges the traditional network security approach, which assumes that devices or users within the internal network are inherently trustworthy. With ZTA, the idea is that every device, user, and request for access is treated as potentially malicious, regardless of its origin. This shift in mindset is particularly important in today’s increasingly complex digital landscape, where threats are often sophisticated, and users can be working remotely or accessing networks through various devices.\n\n"
            "Unlike traditional security models, which often rely on perimeter defenses such as firewalls, intrusion prevention systems, and virtual private networks (VPNs), Zero Trust assumes that the perimeter is no longer a sufficient safeguard. Modern organizations have moved beyond the classic network boundary with cloud computing, mobile devices, and remote workers. As a result, perimeter-based defenses are no longer effective in securing all entry points. ZTA focuses on securing access to resources from the inside out, applying the same level of scrutiny to both internal and external traffic.\n\n"
            "At the core of Zero Trust Architecture is the concept of **identity verification**. ZTA enforces strict identity management processes, ensuring that every user, device, or application requesting access to the network or its resources is properly authenticated. This authentication process typically involves multi-factor authentication (MFA), which requires users to provide more than one form of verification, such as a password and a unique code sent to their mobile device. This helps prevent unauthorized access, even if an attacker has obtained a user’s credentials through phishing or other means.\n\n"
            "In addition to identity verification, Zero Trust Architecture also emphasizes **continuous monitoring** of user and device activity. ZTA doesn’t trust any entity based on past behavior or once-per-session authentication. Instead, it continuously monitors interactions to detect suspicious activities that could indicate a security threat. This approach helps organizations identify anomalies or malicious behavior in real time, reducing the risk of a breach or compromise. Continuous monitoring also helps ensure that if an entity’s behavior changes—such as accessing unusual resources or exhibiting abnormal network activity—the system can quickly respond to mitigate the threat.\n\n"
            "Another key principle of ZTA is **least-privilege access control**. Under this approach, users and devices are granted the minimum level of access required to perform their specific tasks or functions. Rather than granting broad access to the entire network, ZTA ensures that users only have access to the data, applications, or systems they need, based on their role or job function. This reduces the attack surface by limiting the number of resources that can be accessed, even if a user or device is compromised.\n\n"
            "Zero Trust Architecture also involves **micro-segmentation**, which divides the network into smaller, isolated segments to limit lateral movement of threats within the organization. For example, even if an attacker compromises one part of the network, micro-segmentation prevents them from freely moving between different parts of the network. This segmentation is enforced through access controls, firewalls, and other network security mechanisms, ensuring that even trusted users or devices can only access the resources they need, minimizing the potential damage from a security incident.\n\n"
            "The implementation of Zero Trust Architecture is typically driven by the need to secure sensitive data and applications, protect against insider threats, and ensure regulatory compliance. As organizations increasingly migrate to cloud environments, ZTA provides a robust framework for securing access to cloud resources and ensuring that data is protected even in multi-cloud or hybrid environments. ZTA also plays a critical role in securing remote workforces, where traditional perimeter-based defenses are insufficient.\n\n"
            "While Zero Trust Architecture provides a powerful security framework, its implementation can be complex and requires significant planning. Organizations must integrate ZTA with existing security systems, update policies, and invest in advanced technologies for identity management, authentication, and monitoring. However, the benefits of adopting Zero Trust—such as reduced risk of data breaches, improved regulatory compliance, and better protection against cyber threats—make it an increasingly attractive approach for modern organizations.\n\n"
            "In conclusion, Zero Trust Architecture (ZTA) represents a shift in how organizations approach network security, focusing on strict identity verification, continuous monitoring, and least-privilege access controls. By assuming that no entity should be trusted by default and applying stringent security measures to both internal and external access, ZTA reduces the attack surface and helps prevent data breaches. As the security landscape continues to evolve, adopting a Zero Trust framework is becoming an essential part of any comprehensive cybersecurity strategy.",
          videoId: 'yn6CPQ9RioA',
        ),
        '/quiz/advanced_cryptography': (context) => AdvanceQuizScreen(topic: 'Advanced Cryptography'),
        '/quiz/penetration_testing': (context) => AdvanceQuizScreen(topic: 'Penetration Testing'),
        '/quiz/ids': (context) => AdvanceQuizScreen(topic: 'Intrusion Detection Systems'),
        '/quiz/cloud_security': (context) => AdvanceQuizScreen(topic: 'Cloud Security'),
        '/quiz/zero_trust': (context) => AdvanceQuizScreen(topic: 'Zero Trust Architecture'),

      },
    );
  }
}
